config/routes.rb
Rails.application.routes.draw do
  root 'products#index'
  get '/dashboard', to: 'dashboard#index'


  get '/signup', to: 'users#new'
  get '/login',   to: 'sessions#new'
  post '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get '/cart', to: 'carts#show'
  post 'order_items/:id', to: 'order_items#create'
  
  resources :order_items do 
    patch :add_quantity, on: :member
    patch :reduce_quantity, on: :member
  end
  
  resources :carts do
    delete :destroy
  end

  resources :orders, only: %i[create index] do 
    patch :deliver_order, on: :member
  end

  resources :users
  resources :products
  resources :account_activations, only: :edit
  resources :password_resets, only: %i[new create edit update]
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :admin_user, only: :index

  def index
    @products = Product.all
  end

  private 
  
  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end
end

app/views/dashboard/index.html.haml
%p#notice= notice

%h1 Products

%img.logo-dashboard{:alt => "Sunzi Bistro logo", :src => "logo.jpg"}/

%table.dashboard

  %thead.dashboard

    %tr.dashboard
      %th.dashboard &nbsp &nbsp Title &nbsp &nbsp &nbsp &nbsp
      %th.dashboard &nbsp Description &nbsp &nbsp &nbsp &nbsp
      %th.dashboard &nbsp &nbsp Price &nbsp &nbsp &nbsp &nbsp
      %th.dashboard &nbsp &nbsp Image &nbsp &nbsp &nbsp &nbsp
      %th.dashboard{:colspan => "3"}

  %tbody.dashboard
    - @products.each do |product|

      %tr.dashboard
        %td.dashboard= product.title 
        %td.dashboard= product.description 
        %td.dashboard= product.price 
        %td.dashboard= cl_image_tag product.image.key , width: '50px', height: '50px' 
        %td.dashboard= link_to 'Show', product, class: 'btn btn-primary show'
        %td.dashboard= link_to 'Edit', edit_product_path(product), class: 'btn btn-primary edit'
        %td.dashboard= link_to 'Destroy', product, :method => :delete,  class: 'btn btn-primary delete', data: { confirm: 'Are you sure?' }
%br
= link_to 'New Product', new_product_path, class: 'btn btn-primary path-new-dashboard'
%br
= link_to 'Back to Home', root_path, class: 'btn btn-primary path-new-dashboard'