config/routes.rb
Rails.application.routes.draw do
  root 'products#index'
  get '/dashboard', to: 'dashboard#index'


  get '/signup', to: 'users#new'
  get '/login',   to: 'sessions#new'
  post '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get '/cart', to: 'carts#show'
  post 'order_items/:id', to: 'order_items#create'
  
  resources :order_items do 
    patch :add_quantity, on: :member
    patch :reduce_quantity, on: :member
  end
  
  resources :carts do
    delete :destroy
  end

  resources :orders, only: %i[create index] do 
    patch :deliver_order, on: :member
  end

  resources :users
  resources :products
  resources :account_activations, only: :edit
  resources :password_resets, only: %i[new create edit update]
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :order_items
  belongs_to :user
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def show
    @order_items = current_user.cart.order_items
  end

  def destroy
    current_user.cart.order_items.destroy_all

    redirect_to(cart_path)
  end
end

app/helpers/carts_helper.rb
module CartsHelper
  def current_cart
    if !session[:cart_id].nil?
      @current_cart = Cart.find(session[:cart_id])
    else
      @current_cart = Cart.new
    end
  end
end

app/views/carts/show.html.haml
%h1.shoppingcart-title Your Shopping Cart

%img.logo-cart{:alt => 'Sunzi Bistro logo', :src => 'logo.jpg'}  

%ul.shoppingcart-ul
  - @order_items.each do |item|
    %div.shoppingcart
      .shoppingcart-product-title=item.product.title
      %br
      
      =cl_image_tag item.product.image.key, class: 'shoppingcart-image'
      %br

      Price: $#{item.product.price}
      %br

      .shoppingcart-quantity
        ="Quantity: #{item.quantity}"
        =button_to '+', add_quantity_order_item_path(id: item), method: :patch, class:'addButton'
        =button_to '-', reduce_quantity_order_item_path(id: item), method: :patch, class: 'reduceButton'
      %br
        
        =link_to 'Remove Item', item, method: :delete, class: 'btn btn-danger btn-sm'

%div.totalprice 
  ="Total: #{@order_items.to_a.sum { |item| item.total_price }} $"
  %br

  =link_to 'Empty Cart', cart_destroy_path(current_user.cart), method: :delete, class: 'btn btn-danger btn-sm-empty'
  %br

  =link_to 'Place your order', orders_path, method: :post, class: 'btn btn-danger btn-sm-place'
  =link_to 'Go Back!', root_path, class: 'btn btn-primary path-cart'