config/routes.rb
Rails.application.routes.draw do
  root 'products#index'
  get '/dashboard', to: 'dashboard#index'


  get '/signup', to: 'users#new'
  get '/login',   to: 'sessions#new'
  post '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get '/cart', to: 'carts#show'
  post 'order_items/:id', to: 'order_items#create'
  
  resources :order_items do 
    patch :add_quantity, on: :member
    patch :reduce_quantity, on: :member
  end
  
  resources :carts do
    delete :destroy
  end

  resources :orders, only: %i[create index] do 
    patch :deliver_order, on: :member
  end

  resources :users
  resources :products
  resources :account_activations, only: :edit
  resources :password_resets, only: %i[new create edit update]
end

app/models/product.rb
class Product < ApplicationRecord
  has_one_attached :image
  has_many :order_items, dependent: :destroy 
  has_many :order_details, dependent: :destroy 
  has_many :orders
  
  validates :title, presence: true
  validates :price, presence: true, numericality: { :greater_than => 0 }
  validates :description, presence: true
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def index
    @products = Product.all
  end

  def show; end

  def edit; end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params.except(:image))
    @product.image.attach(product_params[:image])

    if @product.save
      flash[:success] = 'Product added successfully!'

      redirect_to(@product)
    end
  end

  def update
    respond_to do |format|
      if @product.update(product_params)
       flash[:success] = 'Product updated successfully!'
       
       redirect_to(@product)
     else
       render 'edit'
     end
   end
  end

  def destroy
    @product = Product.find(params[:id]).destroy
    flash[:success] = 'Product deleted!'

    redirect_to(dashboard_path)
  end

  private

  def product_params
    params.require(:product).permit(:title, :description, :price, :image)
  end

  def set_product
    @product = Product.find(params[:id])
  end

  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end
  
end

app/views/products/_form.html.haml
= form_with(model: product) do |form|
  - if product.errors.any?
    .products#error_explanation
      %h2
        = pluralize(product.errors.count, 'error')
        prohibited this product from being saved:
      %ul.products
        - product.errors.each do |error|
          %li.products= error.full_message
          
  .field
    = form.label :title, class:'dashboard-label'
    = form.text_field :title, class: 'dashboard form-control'

  .field
    = form.label :description, class:'dashboard-label'
    = form.text_field :description, class: 'dashboard form-control'

  .field 
    = form.label :price, class:'dashboard-label'
    = form.text_field :price, class: 'dashboard form-control'

  .field 
    = form.label :image, class:'dashboard-label'
    = form.file_field :image, class: 'dashboard-image',direct_upload: true
    
  .actions
    = form.submit 'Create product',  class: 'dashboard btn btn-primary'
    

app/views/products/edit.html.haml
%h1.dashboard Edit Product

%img.logo-new{:alt => 'Sunzi Bistro logo', :src => '/assets/logo.jpg'}/

= render 'form', product: @product

= link_to 'Back to Dashboard', dashboard_path, class: 'btn btn-primary path-new'
%br
= link_to 'Show Product', @product, class: 'btn btn-primary path-show'

app/views/products/index.html.haml
%body
  %header
    %nav
      .nav
        %img.logo{:alt => "Sunzi Bistro logo", :src => "logo.jpg"}/
        %h3
          \  Sunzi
          %br/
          \  Bistro
        %ul.main-nav
          - if logged_in?
            - if current_user.admin?
              %li= link_to 'Dashboard', dashboard_path
              %li= link_to 'Orders', orders_path
              %li= link_to 'Users', users_path
            %li= link_to 'My Orders', current_user
            %li= link_to 'Settings', edit_user_path(current_user)
            %li= link_to 'Log out', logout_path, method: :delete 
            = link_to '', cart_path, class: 'fas fa-shopping-cart'
          - else 
            %li= link_to 'Log in', login_path
            %li= link_to 'Sign up', signup_path
    
    .description-text-box
      %h1 Ordering Food
      %br/
      %h2
        \~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  
        %i.fas.fa-utensils  
        \~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      %p
        Sunzi Bistro is a well-established restaurant that has been in business for over 10 years.
        You can easily find this restaurant at the Remedios Circle in Malate because of its wooden
        door and green roof.
  
  .features-bar
    .dropdown-for-category
      %button.dropbtn-category
        Categories
        %i.fa.fa-caret-down
      .dropdown-categories
        %a{:href => "#"} Hamburger
        %a{:href => "#"} Noodles
        %a{:href => "#"} Pasta
        %a{:href => "#"} Pizza
        %a{:href => "#"} Sweets
    .dropdown-for-sorting
      %button.dropbtn-sorting
        Sorting
        %i.fa.fa-caret-down
      .dropdown-sorting
        %a{:href => "#"} Sort
    .dropdown-for-vegetarian
      %button.dropbtn-vegetarian
        Vegetarian
        %i.fa.fa-caret-down
      .dropdown-vegetarian
        %a{:href => "#"} Noodlles
    .min-max-slider{"data-legendnum" => "2"}
      %label{:for => 'min'} 0$
      %input#min.min{:max => '150', :min => '0', :name => 'min', :step => '1', :type => 'range'}/

      %label{:for => 'max'} 150$
      %input#max.max{:max => '150', :min => '0', :name => 'max', :step => '1', :type => 'range'}/
      %h6 Price
  
  %br/
  
  %main.products-list
    - @products.each do |product|
      .products 
        =cl_image_tag product.image.key, class:'food-img'
        .food-title= product.title
        .food-description= product.description
        .food-price= "$#{product.price}"
        = button_to 'Add to Cart', "/order_items/#{product.id}", method: 'post', class: 'add abtn abtn-primary'
        %br
        %end
      

app/views/products/new.html.haml
%h1.dashboard New product 

%img.logo-new{:alt => 'Sunzi Bistro logo', :src => '/assets/logo.jpg'}/

= render('form', product: @product)

= link_to 'Back to Dashboard', dashboard_path, class: 'btn btn-primary path-new'

app/views/products/show.html.haml
%p#notice= notice

%img.logo-show{:alt => 'Sunzi Bistro logo', :src => '/assets/logo.jpg'}/

%p.dashboard.title
  %strong Title:
  = @product.title

%p.dashboard
  %strong Description:
  = @product.description

%p.dashboard
  %strong Price: 
  = @product.price 
  
%p
  %strong Image: 
  = cl_image_tag @product.image.key, width: '200px', height: '270px' 

= link_to 'Edit Product', edit_product_path(@product), class: 'btn btn-primary path-edit'
%br
= link_to 'Back to Dashboard', dashboard_path, class:'btn btn-primary path-edit'